### ISSUE TITLE
Präsentation Requirements

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#1]

**Comment by mathiasstocker** [comment]
Treffen mit @dominikfankhauser um Montags-Präsentation zu besprechen

Aufwand: 0.5 Stunden

**Comment by mathiasstocker** [comment]
Erstellung Präsentation

Aufwand: 4.5 Stunden

**Comment by mathiasstocker** [comment]
Telefonische Besprechung mit @dominikfankhauser

Aufwand: 0.25 Stunden

**Comment by dominikfankhauser** [comment]
Überarbeitung und Vorbereitung Präsentation.

Aufwand: 2.5 Stunden
