### ISSUE TITLE
Kundentests: Unterlagen für die verschiedenen Rollen/Use-Cases

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#103]
Test/Feedback-Unterlagen bereitstellen.

Aktueller Stand Verfügbarkeit (gemäss Kunde):

Christina als Sekretariat und Tourenleiterin ist ab Osterdienstag verfügbar.
Gallus als Kassier am 21./22. April und ab 01.05.2017 verfügbar.
Ruedi als Tourenchef und Tourenleiter ab 24.04. verfügbar.
Franziska als Redaktion ab Osterdienstag vefügbar . 26.-29.04.2017 abwesend.
Bettina als Tourenchef und Tourenleiter BCB Jugend ab 24.04.verfügbar.
Esther als Mutationen ist verfügbar.
Meine Wenigkeit ist verfügbar.
Tourenleiter die bis jetzt nicht involviert waren:
Jürg Anliker, Tourenleiter
Elisabeth Christen Nussbaum

**Comment by mathiasstocker** [comment]
Tschau Mathias
So, nun habe ich alle Probanden die ich gerne für den Testbetrieb involvieren möchte. So können wir davon ausgehen dass wir mit guten Rückmeldungen bedient werden. Der genaue Ablauf werdet Ihr ja noch bekanntgeben. 

Christina Arnold als Sekretariat und Tourenleiterin ist ab Osterdienstag verfügbar.
Gallus als Kassier am 21./22. April und ab 01.05.2017 verfügbar.
Ruedi als Tourenchef und Tourenleiter ab 24.04. verfügbar.
Franziska als Redaktion ab Osterdienstag verfügbar . 26.-29.04.2017 abwesend.
Bettina als Tourenchef und Tourenleiter BCB Jugend ab 24.04.verfügbar.
Esther als Mutationen ist verfügbar.
Meine Wenigkeit ist verfügbar.
Tourenleiter die bis jetzt nicht involviert waren:
Jürg Anliker, Tourenleiter
Elisabeth Christen Nussbaum
Eva Maria Knaus, Tourenleiterin

Weitere Testpersonen
Denise Dick, kein Mitglied, ist aber ausgebildet mit Beurteilungen über benutzerfreundliche Web-Seiten.
Brigitte Sacker, Mitglied BCB

Zukünftiger Administrator:
Sirai Zaugg

**Comment by ilcoron** [comment]
Aufwand: 4 Stunden

**Comment by ilcoron** [comment]
Aufwand: 4 Stunden
