### ISSUE TITLE
Plugin Skeleton erstellen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#11]
Als Entwickler möchte ich ein Plugin mit folgender Funktionalität:

- Ein Menüpunkt im Admin erstellen
- Dieser Link sollte eine Seite rendern
- [Optional] Datenbankänderung

**Comment by dominikfankhauser** [comment]
In Plugin-Entwicklung eingearbeitet und anschliessend erste Funktionen implementiert (Menü zum Adminbereich hinzufügen, Einstellungen hinzufügen etc.)

Aufwand: 6 Stunden
