### ISSUE TITLE
Touren erfassen - Dropdown BCB / BCB Jugend / beide

### ISSUE THREAD

**Issue by Tschav** [PSEBergclubBern/BergclubBern#114]
Leiter Jugend sieht entsprechend nur BCB Jugend

**Comment by kreemer** [comment]
Aufwand: 0.5 Stunden

**Comment by mathiasstocker** [comment]
Noch nötig:
Auflistung unter Touren/Tourenbericht je nach Rechte nur BCB oder nur Jugend (jeweils + "Beide") anzeigen.

**Comment by mathiasstocker** [comment]
Es werden nun je nach Capability (touren_bcb, touren_jugend) unter "Touren" resp. "Tourenberichte" nur folgende eingeblendet:
- Nur "BCB" und "Beide"
- Nur "Jugend" und "Beide"
- "BCB", "Jugend" und "Beide"

Falls beide capabilities vorhanden sind, wird zudem bei "Touren" eine zusätzliche (sortierbare) Spalte eingeblendet, die es erlaubt nach diesem Feld zu sortieren.

Aufwand: 0.5 Stunden
