### ISSUE TITLE
Benutzerhandbücher erfassen

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#119]
### Tourenleiter:
- [x] Tourentwurf erfassen
- [x] Tour vollständigen erfassen und zum Review freigeben
- [x] Spesenverwaltung / Tourenrückmeldung erfassen

### Tourenchef:
- [x] Tourenentwurf reviewen
- [x] Tour publizieren
- [x] Spesen / Tourenrückmeldung freigeben
- [x] Export Touren

### Mutation:
- [x] Adressverwaltung Allgemein
- [x] Adressverwaltung Ehepaare
- [x] Export Mitgliederliste / Versandliste

### Redaktion:
- [x] Mitteilung erfassen
- [x] Pages (Seiten) anpassen
- [x] Tourenbericht erfassen
- [x] Tourenbericht Bilder hinzufügen
- [x] Export / Druck
- [x] Tourenrückmeldungen bearbeiten (nur Kurzbericht zu Tour)

### Kasse:
- [x] Spesen als bezahlt markieren
- [x] Export Mitgliederbeiträge

### Internet:
- [x] Hingergrundbilder ändern
- [x] Stammdaten verändern
- [ ] Pages (Seiten) anpassen, evtl. ausführlicher als Redaktion z.B. Seite hinzufügen (?)

**Comment by Tschav** [comment]
Erstellen LaTex File; Erstellen Screenshots und bearbeiten; Schreiben einer ersten Fassung des Handbuchs betreffend Adressverwaltung

Aufwand: 7.75 Stunden

**Comment by dominikfankhauser** [comment]
Abschnitt über Ehepartner hinzugefügt.

Aufwand: 1 Stunde

**Comment by Tschav** [comment]
Abschnitt Export zu Adressverwaltung hinzugefügt

Aufwand: 1 Stunde

**Comment by Tschav** [comment]
Erster Entwurf Tourenleiter Handbuch erstellt

Aufwand: 4.5 Stunden

**Comment by Tschav** [comment]
Erster Entwurf Tourenchef Handbuch erstellt

Aufwand: 1 Stunde

**Comment by Niroth** [comment]
Handbuch Internet und Redaktion zu einem Grossteil erstellt, es fehlen überall noch die Teile der Tourenrückmeldung, sowie das Einfügen von Bildern in Tourenberichten in der Redaktion. Für die Kasse wurde zudem der kurze Exportteil erstellt.

Aufwand: 8 Stunden

**Comment by Niroth** [comment]
Handbuch Kasse und Redaktion grob abgeschlossen.

Aufwand: 1.5 Stunden
