### ISSUE TITLE
Konzept zur technologischen Abdeckung der Use Cases erstellen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#12]

**Comment by kreemer** [comment]
Erster Entwurf hochgeladen, SRS durchgeschaut

Aufwand: 2 Stunden

**Comment by mathiasstocker** [comment]
Feedback in Pull Request angebracht.

Aufwand: 0.25 Stunden

**Comment by kreemer** [comment]
Konzept verbessert, Issues im Backlog erstellt

Aufwand: 3.5 Stunden
