### ISSUE TITLE
Distanz (km) hinzufügen zu Tour

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#121]

**Comment by kreemer** [comment]
wird nicht validiert? oder einfach mit is_Numeric?
@mathiasstocker

**Comment by mathiasstocker** [comment]
Ich würde "is_numeric" und bei der Benennung "Distanz (km)". Dann können wir dort wo wir es anzeigen "km" dazuschreiben - ansonsten ist es dann mal mit mal ohne - Machen wir bei den Höhenmetern auch so oder? Falls Höhenmeter nur überprüft werden ob nicht leer, dann würde ich es auch so machen, also einfach Pflichtfeld mit freitext.

**Comment by kreemer** [comment]
Aufwand: 0.5 Stunden
