### ISSUE TITLE
Erstes (vtl. statisches) Theme erstellen, Bootstrap einbinden

### ISSUE THREAD

**Issue by kellenberger** [PSEBergclubBern/BergclubBern#13]
Bootstrap einbinden/erstes (einfaches) Theme erstellt, auf neuem Branch first_theme abgelegt

Aufwand: 5 Stunden

**Comment by kellenberger** [comment]
Loop zu Index hinzugefügt. Design verbessert.

Aufwand: 2 Stunden

**Comment by Tschav** [comment]
Standard Header hinzugefügt; WP-admin kann Menu anpassen

Aufwand: 3.5 Stunden

**Comment by Tschav** [comment]
Menu und Pages werden im Code generiert

Aufwand: 2.5 Stunden
