### ISSUE TITLE
Neuer Tourenbericht: Feld Youth wird nicht gespeichert

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#133]

**Comment by kreemer** [comment]
Import nicht vergessen

**Comment by mathiasstocker** [comment]
=> Kein Bug. Tourenberichte haben einfach noch kein Feld isYouth (Touren haben dieses Feld) müsste einfach von Tour übernommen werden beim Speichern.

**Comment by kreemer** [comment]
Aufwand: 1 Stunde
