### ISSUE TITLE
Tourenberichte um Lightbox erweitern, damit Bilder hochgeladen werden können

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#134]

**Comment by kellenberger** [comment]
Lightbox implementiert. Die Bilder werden vor dem Content angezeigt und müssen sich in einer Gallerie befinden. Alle Bilder im Content, die sich nicht in der Gallerie befinden, werden nicht angezeigt. 

Aufwand: 4.5 Stunden
