### ISSUE TITLE
Feedback: Adressverwaltung: Geburtsdatum

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#151]
Vom Kunden:
Es kann sein, dass ich das genaue Geburtsdatum nicht habe, oder als Interessent überhaupt  noch keines. Ich habe z.B. 00.00.1950 eingegeben. Dann erscheint 30.11.1949.

**Comment by kreemer** [comment]
Abklären wie der aktuelle Stand ist
Aktueller Stand mit SRS abgleichen FA-05

**Comment by mathiasstocker** [comment]
Bei Inserent ist Geburtsdatum kein Pflichtfeld.
Gemäss SRS nicht eindeutig ob es als Textfeld oder als Datumsfeld gehandhabt wird.
Mit Kunde zwei Varianten in Abklärung:
- Als String behandeln (nicht leer, wenn Pflicht)
- Weiterhin als Datum behandeln, jedoch vor Umwandlung in Datum noch tag, monat & jahr Kombination validieren mit checkdate (00.00.1950 würde dann nicht mehr zugelassen) => Bei dieser Variante würde dan z.B. jeweils 01.01.1950 eingegeben und im Kommentar vermerkt, dass nur Jahrgang bekannt.

**Comment by mathiasstocker** [comment]
Mit Kunde besprochen (Variante 2 umgesetzt)

Aufwand: 0.25 Stunden
