### ISSUE TITLE
Feedback: Adressverwaltung: Export

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#152]
Kunde:

- [x] Beim Export Versandliste erscheint nur die Excel-Liste. Ist es möglich, dass die Adressen direkt auf einem Etikettenformular erscheinen, oder muss ich selber mittels Serienbrief, oder wie das heisst, Etiketten erstellen. Vorher erschienen die Adressen direkt auf Etiketten.

- [x] Auf Export Versandliste komplett erscheinen die Ehepaare mit „Herr und Frau Armin & Arnold“ anstatt Herr und Frau Armin & Christina Arnold.

- [x] Auf Export Versandliste Programm erscheinen Arnold’s überhaupt nicht.

**Comment by Tschav** [comment]
Export Versandliste Vorname beider Ehepartner wird angezeigt

Aufwand: 0.5 Stunden

**Comment by mathiasstocker** [comment]
Etikettenformular nicht möglich.
Feedback an Kunde muss noch gemacht werden (wer übernimmt das? Timm oder ich?)

**Comment by mathiasstocker** [comment]
Letzter Punkt wird bei Import anscheinend nicht korrekt gesetzt.
@kreemer ist da dran.

**Comment by kreemer** [comment]
@mathiasstocker meinst du #169, ist dies jetzt gelöst?

**Comment by mathiasstocker** [comment]
Yup, ist gelöst.
