### ISSUE TITLE
Rückmeldung als Leiter nicht korrekt angezeigt

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#160]
Mir ist folgendes passiert, als ich als Leiter versucht habe die eben von mir erfasste Rückmeldung zu editieren:
![bug](https://cloud.githubusercontent.com/assets/18282099/25565603/68b0bb18-2dca-11e7-9172-7871ff3b7fca.PNG)

Es wird versucht, dass dateApproved anzuzeigen, obwohl es noch nicht gesetzt wurde.

**Comment by dominikfankhauser** [comment]
Aufwand: 0.5 Stunden
