### ISSUE TITLE
Touren in der Vergangenheit aus Admin Bereich erreichbar machen

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#162]
Beim Bearbeiten der Tour wird ein Link angezeigt, wenn die Tour in der Vergangenheit liegt, ist dieser Link aber ungültig.
Scheint falsch zu sein, weil man 404 bekommt.
Aber vielleicht ist das so gewünscht.

**Comment by Tschav** [comment]
Bug behoben

Aufwand: 1.5 Stunden
