### ISSUE TITLE
Benutzerhandbuch korrigieren

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#163]
- [ ] Adresse
- [ ] Internet
- [ ] Kasse
- [ ] Tourenchef
- [ ] Redaktion
- [ ] Tourenleiter

**Comment by kellenberger** [comment]
Teil Tourenbericht kontrolliert und überarbeitet.

Aufwand: 1 Stunde

**Comment by dominikfankhauser** [comment]
Kasse, Internet, Adressverwaltung, Tourenleiter (Teil Tourenrückmeldung) und Tourenchef (Teil Tourenrückmeldung) durchgeschaut und wo nötig korrigiert. Dabei ist mir folgendes aufgefallen:

- Im Handbuch für den Tourenchef ist im Bereich der Tourenrückmeldungen nicht erfasst, dass er den Leiter sowie den Co-Leiter einer Tour ändern kann. Soll dieser Teil noch hinzugefügt werden oder nicht?

Aufwand: 2.5 Stunden

**Comment by ilcoron** [comment]
Ticket löst Teile von #198

**Comment by dominikfankhauser** [comment]
Alle Handbücher noch einmal durchgegangen, überarbeitet und so weit wie möglich sprachlich vereinheitlicht.

Aufwand: 5 Stunden

**Comment by kellenberger** [comment]
Wiederum Bilderworkflow korrigiert. Ganzes Handbuch Korrekturgelesen

Aufwand: 1.5 Stunden
