### ISSUE TITLE
Feedback: Redaktion: Bilder kann man nicht hochladen

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#172]
Lieber Peter,
 
ich habe die "Aufgaben" für die Redaktion durchgespielt, soweit problemlos. Hingegen gibt es Schwierigkeiten beim Fotos-Hochladen, da auf der Webseite die Rubrik "Dateien hinzufügen" für mich nicht ersichtlich ist. Das Handbuch bringt deshalb (im Moment) nichts. Sobald ich auf die Fotoseite gelangen kann, werde ich mir diese Rubrik auch noch genauer anschauen. HELP!
 
Liebe Grüsse
Franziska

**Comment by ilcoron** [comment]
Wenn man sich als Redaktion einloggt, sieht man den "Dateien hochladen" Button nicht.

**Comment by mathiasstocker** [comment]
Aufwand: 0.25 Stunden
