### ISSUE TITLE
Feedback: Redaktion: Quartalsheft

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#173]
Lieber Peter,
 
ich habe jetzt noch (ohne Auftrag) die Seite Export/Druck noch etwas angeschaut. Da hätte ich gerne eine Berechtigung, die Formatierung des Quartalheftes anzupassen, sonst muss man das dann bei jeder Publikation händisch machen. Würde viel Arbeit ersparen. Vielen Dank.
 
Franziska

**Comment by mathiasstocker** [comment]
Geht nicht, es gibt keinen Online-Editor für das.
Vorher war es eine HTML-Seite die generiert wurde und per Copy-Paste ins Word eingefügt wurde - da konnte die Formatierung soviel ich weiss auch nicht von der Redaktion angepasst werden.
Ich habe mich an der bisherigen Funktion orientiert...

**Comment by kreemer** [comment]
gleich schliessen?
