### ISSUE TITLE
Feedback: Tourenleiter: Dauer etc

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#179]
Aus Mail von Peter:

Unter Leiter hat es geklappt.
Habe die mehrtägige Tour Alpenpässe iii Lac d’Emosson-La Fouly eingegeben.
Bei den Tourendaten bei **Auf - und Abstieg fehlen die weiteren Tage**. Lösung wie in der Testerfassung möglich.
Programm für den ersten Tag, die **weiteren Tage fehlen**. Lösung wie in der Testerfassung möglich.
Bei der Anmeldung sollten noch **Felder für die Telefonnummer und E-Mail** eingepflegt werden sonst wird es vermutlich hin und wieder vergessen.
Bei **Dauer kann die Verarbeitung nicht erfolgen** da die Einträge für 3 Tage  1.Tag 7:00 2.Tag 8:00 3.Tag 6:30 hinterlegt sind. Es wird ein Validierungsproblem angezeigt. Die Weiterverarbeitung beim Tourenchef zur Freigabe kann möglicherweise nicht erfolgen. In der Vorschau wird aber die Zeitdauer korrekt angezeigt.

**Comment by mathiasstocker** [comment]
**Dauer:**
Siehe #177

**Felder für die Telefonnummer und E-Mail:**
Peter meint damit, dass wenn "Anmeldung an" ausgewählt ist, im Frontend keine Telefonnummer/Email angezeigt wird. Dies ist, weil die Testleiter keine Email und/oder Telefonnummern hinterlegt hatten.

Rest i.O. (Aufstieg, Abstieg, Distanz mehrtägige wird einfach "Tag 1: ..., Tag 2: ...," geschrieben.)

**Comment by kreemer** [comment]
Nur für die klarheit

Aufstieg: Neu textarea, wird nur überprüft ob nicht leer
Abstieg: Neu textarea, wird nur überprüft ob nicht leer
Programm: ?
Distanz: ?

**Comment by mathiasstocker** [comment]
Habe mich beim PR nicht geachtet, dass du Textarea gemacht hast. Würde ich nicht, weil da ist immer die Frage wie man multiline (\n) behandelt. Würde Singleline (input type text) belassen (gemäss SRS, Singleline was Singleline war)

Es sind weiterhin alles Pflichtfelder gemäss SRS jedoch keine Formatkontrolle bei:
Aufstieg, Abstieg, Distanz, Dauer

**Comment by ilcoron** [comment]
Aufstieg: input type="text", wird nur überprüft ob nicht leer
Abstieg: input type="text", wird nur überprüft ob nicht leer
Programm: textarea, wird nur überprüft ob nicht leer
Distanz: input type="text", wird nur überprüft ob nicht leer
Dauer: input type="text", wird nur überprüft ob nicht leer
Anzeige Dauer: Es wird jetzt nicht mehr automatisch " Stunden" angehängt.

**Comment by ilcoron** [comment]
Aufwand 0.5 Stunden
