### ISSUE TITLE
Adressverwaltung Übersichtsseite erstellen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#19]
Als Verantwortliche Person möchte ich die Adressen des Vereins verwalten
- [ ] Die Rechte / Gruppen für die Adressverwaltung sollte automatisch generiert werden
- [ ] Tabellen erstellen für die Adressverwaltung mit den benötigten Felder
- [ ] Testdaten befüllen
- [ ] Liste im WP-Admin Modul erstellen um Übersicht über die erstellen Testdaten zu erhalten

**Comment by mathiasstocker** [comment]
Erledigt:
* Erweitern der User mit Metadaten (noch nicht alle).
* Kleine Menge an Testdaten erstellt.
* Liste (Plugin-Übersichtsseite) erstellt

Noch offen:
* Rechte / Gruppen generieren, klar wies geht.
* Weitere Testdaten => evtl. über Export/Import alte DB

Aufwand: 3 Stunden

**Comment by mathiasstocker** [comment]
Erledigt bis auf :
Liste im WP-Admin Modul erstellen um Übersicht über die erstellen Testdaten zu erhalten
Aufwand unter "Neue Adresse erstellen / alte Mutieren" erfasst.

**Comment by mathiasstocker** [comment]
Erledigt, Testlogins im Plugin > Submodul Adressverwaltung > README.md erklärt
