### ISSUE TITLE
Bilderhandling generell im Frontend analysieren und abstimmen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#190]
Mitteilungen etc. beachten und eventuell Info-Boxen einblenden um auf die Funktionalität hinzuweisen.

**Comment by kreemer** [comment]
@mathiasstocker

**Comment by kellenberger** [comment]
Bilderhandling angepasst:
Es werden nun alle Bilder aus dem Content entfernt und am Beginn als Lightboxshow angezeigt.
Ich musste leider feststellen, dass die Bilder nur bei jenen Post  direkt als attachement via wp-Funktion verfügbar sind, bei denen sie hochgeladen wurden. Deshalb werden die Ids der Bilder nun mühsam mittels Regex aus dem Content extrahiert.
Das alles geschieht nun mittels Filter bereits beim Aufruf des Contents.

Aufwand: 4 Stunden
