### ISSUE TITLE
Handbuch Anpassen Adressverwaltug Export

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#194]
Bitte beim Handbuch Adressverwaltung unter Export noch einen Hinweis anbringen im Stil von:
Eine Anleitung zur Erstellung von Etiketten in Word finden Sie hier: http://bit.ly/word-etiketten

**Comment by Niroth** [comment]
@Tschav Ich habe es einfach als "Hinweis:" eingefügt. Hast du für solches eine Formatierung vorgesehen?

Aufwand: 0.5 Stunden

**Comment by Tschav** [comment]
@Niroth Ich habe noch eine fancy Box um den Hinweis gemacht, um es noch etwas hervorzuheben.

**Comment by mathiasstocker** [comment]
Sehr "fancy" ;)
Für mich i.O. - könnt von mir aus closen...
