### ISSUE TITLE
Feedback: Tourenleiter: Touren eingeben

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#195]
Hier mehr Feedback, meine Anmerkungen in _italic_.

Aufgabe: Erfassen Sie eine neue Tour, damit der Tourenchef sich einen Überblick über die möglichen Touren machen kann. Geben Sie dazu nur die wichtigsten Daten ein, und legen Sie diese Tour dann zur Revision vor.

Gab es Probleme bei der Ausführung? JA

Wenn ja, welche?
Zur Revision freigeben: Problem war folgendes: wir haben vergessen, den Titel der Tour einzugeben und haben die Tour dann trotzdem zur Revision freigegeben. Dann erschien der Hinweis „Titel vergessen“, aber alle unsere bereits gemachten Einträge dieser Tour waren weg.
_--- Mist. Können wir hier überhaupt was machen? Oder ist das WP?_
_--- Mathias: Ist bereits diskutiert und von Kevin gelöst worden (im master branch)_

Wenn ja,  konnte das Problem mit Hilfe des Handbuchs gelöst werden? NEIN

WEITERE BEMERKUNGEN:
Leiter: nur Test zu Auswahl statt alle Leiter, Leiter erscheinen nicht (wegen Testversion?)
_--- Ja._

Co-Leiter: in der Liste erscheinen alle Mitglieder statt nur die Leiter
_--- Das ist wirklich ein Task. #199 _
_--- Mathias: Nein kein Task, wurde so an der Marathonsitzung festgelegt und ist unter FA-09 im SRS exakt so aufgeführt (Auflistung aller Personen die eine Mitgliederrolle haben). Grund siehe mein Kommentar #199), habe dies auch Peter so mitgeteilt_

Anmeldung an: es erscheint keine Liste mit den Leitern zur Auswahl
_---Ich dachte man kann sich nur bei den Leitern anmelden?_
_---Mathias: Wurde auch so definiert während der Marathonsitzung und ist im SRS, FA-09_

Anforderungen: viel zu lange Liste, die sich wiederholt, nicht übersichtlich
_--- Nicht unwahr, aber entweder wir werfen die Anforderungen aus dem Fenster und dann ärgern sie sich, dass die Tourendaten immer unvollständig sind, oder behalten sie._
_--- Mathias: Sehe ich genauso und habe das auch Peter mitgeteilt (10 Felder sind auch bei schönster Anordnung/Gruppierung unübersichtlicher als 3 Felder)_

Zuunterst Titelform: was ist das?
_--- Weiss ich auch nicht, ist glaube ich neu._
_--- Mathias: Keine Ahnung was damit gemeint ist, habe nachgefragt_

Format Datum und Kosten: es wäre hilfreich, wenn bereits ein Platzhalter im richtigen Format im Feld vorhanden wäre.
_--- Oder die Validierung weg..._
_--- Oder einfach so lassen wie es ist, Datum kann bereits jetzt mit 03.02.2017, 3.2.2017, 3.2.17 erfasst werden (dachte zuerst das gehe nicht wegen Validierung geht aber in online version - viellecht auch bug?) und das Währungsformat in der Schweiz ist ja 0.00. Ansonsten das placeholder attribut verwenden dort wo das HTML Feld generiert wird (placeholder = "0.00")._

**Comment by kreemer** [comment]
Seperates Issue für Titelform (#200)

**Comment by ilcoron** [comment]
Aus Matthias Mail an Peter:
«Zur Revision freigeben: Problem war folgendes: wir haben vergessen, den Titel der Tour einzugeben und haben die Tour dann trotzdem zur Revision freigegeben. Dann erschien der Hinweis „Titel vergessen“, aber alle unsere bereits gemachten Einträge dieser Tour waren weg.»
Dies ist bereits behoben und wird mit dem nächsten Deployment auch auf bergclub-test.ch so sein.

«Leiter: nur Test zu Auswahl statt alle Leiter, Leiter erscheinen nicht (wegen Testversion?)»
Genau, das ist nur in der Testversion so.

«Co-Leiter: in der Liste erscheinen alle Mitglieder statt nur die Leiter»
Das wurde klar so definiert an der Marathonsitzung und im SRS (FA-09) dass dort alle erscheinen sollen, die eine Mitgliederrolle haben.
Bei Bergtouren ist dort manchmal ein Leiter eingetragen. Bei Wanderungen kann es auch ein Mitglied sein.

«Anmeldung an: es erscheint keine Liste mit den Leitern zur Auswahl»
Ist so vereinbart, es erscheint der aktuell gewählte Tourenleiter und (falls gewählt) der Co-Tourenleiter zur Auswahl in diesem Feld.

«Anforderungen: viel zu lange Liste, die sich wiederholt, nicht übersichtlich»
Mir ist unklar was sich wiederholt? Da es relativ viele Angaben sind (von euch gefordert) wird es aus meiner Sicht dadurch auch etwas weniger unübersichtlich, als wenn man nur 3 Angaben machen müsste.

«Zuunterst Titelform: was ist das?»
Ich habe keine Ahnung was damit gemeint ist, kannst du das abklären oder evtl. Screenshot organisieren?
_Das hat Kevin schon gemacht: #201

«Format Datum und Kosten: es wäre hilfreich, wenn bereits ein Platzhalter im richtigen Format im Feld vorhanden wäre.»
Format Datum als Platzhalter finde ich etwas übertrieben. Zum einen gibt es das Kalender-Tool welches erscheint zum anderen werden diverse gängige Formate unterstützt.
z.B. 01.03.2017, 1.3.2017, 1.3.17 u.s.w.

Bei den Kosten ist es das normale Schweizer Währungsformat 0.00
