### ISSUE TITLE
Feedback: Tourenleiter: Tourenrückmeldungen

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#196]
Hier mehr Feedback, meine Anmerkungen in _italic_.

Aufgabe: Fügen Sie eine Rückmeldung zu einer bereits durchgeführten Tour (Testtour Leiter) hinzu.

Gab es Probleme bei der Ausführung? JA

Wenn ja, welche?
Bei Teilnehmer BCB erscheint keine Liste der Mitglieder zur Auswahl
_--- ist auf nicht geplant_

Wenn ja,  konnte das Problem mit Hilfe des Handbuchs gelöst werden? NEIN

**Comment by ilcoron** [comment]
Aus Mail von Matthias an Peter:
Touren-Rückmeldung: "Bei Teilnehmer BCB erscheint keine Liste der Mitglieder zur Auswahl"
Gerade dieser Punkt wurde an der Marathonsitzung relativ lange diskutiert. Wenn es mir Recht ist, war es Bettina (Jugendleiterin) die gesagt hat, dass es für Leiter praktischer ist, wenn sie sich nicht für jeden Teilnehmer durch eine Liste klicken müssen sondern Ihre Liste direkt «abtöggelen» können.
Es wurde auch überlegt ob aus irgendeinem Grund hier eine Verknüpfung zum Mitglied im Adressstamm benötigt wird und keiner gefunden, aus diesem Grund hat man gesagt man macht es einfach über ein mehrzeiliges Textfeld und zählt die Zeilen (SRS FA-12).

**Comment by ilcoron** [comment]
Mathias: Ist bereits diskutiert und von Kevin gelöst worden (im master branch)

**Comment by mathiasstocker** [comment]
Ist aus meiner Sicht nicht nice-to-have.
Wurde an der Sitzung lange diskutiert ob sie das wollen und pros- und kontra abgewägt.
