### ISSUE TITLE
Feedback: Sekreteriat & Tourenleiterin: Diverses

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#197]
Rückmeldung Testlauf Bergclub, Christina Sekretariat und Tourenleiterin

Anwenderproblem:
Konnte die Tour erfassen
Konnte die Tour bearbeiten
Die Tourenrückmeldung konnte ich bei zwei verschiedenen Tests nicht ausführen.
Fehlermeldung: 404 Seite nicht gefunden
Konnte an Hand des Handbuches den Fehler nicht finden und korrigieren

_--- Hmm schwierig zu sagen was hier falsch gelaufen ist. Wenn natürlich alle Leiter versuchen Rückmeldungen zu geben, gibt es keine mehr.
Wie es zu dem 404er gekommen ist.... Keine Ahnung._

Bei der Distanzangabe fehlt nach meinem Gefühl der Leerschlag  (18km, 18 km)

Im Vorschaufenster hat es einen Schreibfehler bei Verpflegung
_--- ist glaube ich schon geflickt_

Die Fenster für Info Verpflegung, Programm und Ausrüstung ist zu klein, damit man direkt beim Schreiben eine Übersicht erhält. Wohl sieht man das Geschriebene bei der Vorschau, aber es ist mühsam für Korrekturen wieder zum Bearbeiten zurück zu kehren.
_--- machen wir das?_

Um wirklich „sattelfest“ bei den Angaben zu sein, wäre eine praktische Einführung sinnvoll, wo man anhand der Anleitung noch genauer orientieren kann.

**Comment by ilcoron** [comment]
Die Tourenrückmeldung konnte ich bei zwei verschiedenen Tests nicht ausführen.
Fehlermeldung: 404 Seite nicht gefunden
Konnte an Hand des Handbuches den Fehler nicht finden und korrigieren
--- Hmm schwierig zu sagen was hier falsch gelaufen ist. Wenn natürlich alle Leiter versuchen Rückmeldungen zu geben, gibt es keine mehr.
Wie es zu dem 404er gekommen ist.... Keine Ahnung.

**Comment by mathiasstocker** [comment]
Ich habe Peter gefragt ob er die entsprechende Person fragen kann ob Sie das Problem reproduzieren kann und falls ja, uns die URL zustellen kann.

**Distanzangabe**
Wo soll das sein? Kannst du das bitte abklären Timm?

**Die Fenster für Info Verpflegung, Programm und Ausrüstung ist zu klein**
Das ist das einzige was ich eventuell noch anpassen würde.

**Comment by ilcoron** [comment]
Ich habe dieses Ticket in mehrere kleine Tickets unterteilt.
