### ISSUE TITLE
Feedback: Tourenleiter und -Chef: Diverses

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#198]
Hier mehr Feedback, meine Anmerkungen in _italic_.

Lieber Peter
 
Ruedi und ich haben die Tests zusammen gemacht. Im Anhang findest du unsere Anmerkungen für die beiden Rollen „Tourenleiter" und „Tourenchef" wie gewünscht direkt in den Formularen. Darüber hinaus noch folgende Hinweise:
 
Öffentliche Seite
Touren: besser als eine einzige fortlaufende Liste (wie bis anhin) statt mit Seiten 1, 2, 3, 4 usw.  (da mühsam zum Blättern)
_--- ... Was meint ihr hierzu? Was suchen die denn in den Touren?_
Kalender herunterladen: es sollte zusätzlich noch eine Version nicht im Kalenderformat geben, sondern einfach als fortlaufende Liste im pdf (sonst muss sich einer 12 Seiten ausdrucken, auch wenn die Liste der Touren (z.B. der JO) auf einer einzigen Seite Platz hätte)
_--- Wie hoch ist der Aufwand?_
 
Handbuch
Das Handbuch enthält ziemlich viele Sprachfehler. Falls die Handbücher den Leitern abgegeben werden sollen, sollte sie vorher noch jemand sprachlich verbessern. 
 _ --- Machen wir eh schon, oder?_
 
Liebe Grüsse, 
Bettina und Ruedi

**Comment by mathiasstocker** [comment]
Habe Peter geschrieben.

**Fortlaufende Liste:**
Die Performance (Seitenladezeit) leidet, wenn wir alle Touren einblenden. Ich habe ihm gesagt dass wir die Anzahl die angezeigt wird etwas erhöhen können, falls erwünscht.

Habe jetzt gerade festgestellt, dass ich dies bereits mit den WP-Settings gekoppelt habe ;)
Admin => Einstellungen => Blogseiten zeigen maximal [Anzahl] Beiträge

Das heisst Sie können diesen Wert von mir aus auf 1000 Stellen wenn Sie wollen

**Kalender zusätzliche Liste:**
Warte auf Antwort Pesche, habe ihm Mitgeteilt dass aus meiner Sicht an der Marathonsitzung festgelegt wurde, dass Kalenderexport (PDF) reicht und im Admin ein Excel-Export mit Toureninfos.
Wäre rechter Aufwand (wie mit jedem Export den man in ein Format macht welches Textformatierung etc beinhaltet).

**Comment by ilcoron** [comment]
Neue Tickets erstellt
