### ISSUE TITLE
Neue Adresse erstellen / alte mutieren

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#20]
Als Adressverantwortlicher, möchte ich neue Adressen erstellen / mutieren können

- [ ] Formular erstellen zum erstellen / ändern einer Adresse
- [ ] Funktion implementieren

**Comment by dominikfankhauser** [comment]
Formular zum Ändern der Benutzerdaten sowie Speicherfunktion erstellt (noch ohne Validierung).

Aufwand: 3 Stunden

**Comment by mathiasstocker** [comment]
Meeting mit @dominikfankhauser - pair programming (roles, capabilities)

Aufwand: 5.5 Stunden

**Comment by mathiasstocker** [comment]
User und Role Model (benötigt für Adressverwaltung) erweitert.

Aufwand: 5 Stunden

**Comment by mathiasstocker** [comment]
History für Rollen in User Model integriert. Anzeige und Bearbeiten von Funktionsrollen und Historie integriert.

Aufwand: 4.5 Stunden

**Comment by mathiasstocker** [comment]
Noch offen:
- Benutzer editieren: Momentan werden alle möglichen Felder angezeigt und ohne Validierung gespeichert
- Rechte überprüfen für Anzeige/Editieren der Adressen

**Comment by mathiasstocker** [comment]
README erstellt (MVC und Adressverwaltung), Generierung Test User pro Funktionsrolle.

Aufwand: 2.5 Stunden

**Comment by mathiasstocker** [comment]
* Diverse Anpassungen an User Objekt und Adressverwaltung vorgenommen
* Rechte / Capabilities angepasst
* Ansichts- und Bearbeitungsrechte werden überprüft (Ausblenden Editieroptionen und Verweigerung durch Controller falls ungenügend)

Folgendes fehlt noch:
* Validierung der Daten beim ändern Benutzer
* Neuen Benutzer erfasssen

Aufwand: 3.5 Stunden

**Comment by dominikfankhauser** [comment]
Validierung für das Editieren eines Benutzers hinzugefügt. Die Felder werden nur noch abhängig vom Adresstyp angezeigt. Zusätzlich wird das Formular zum Anzeigen der Felder nun aus einem Array heraus generiert.

Folgendes muss noch korrigiert werden:

* Wenn kein Geburtsdatum eingegeben wird (leerer String), wandelt die Funktion setBirthdate($value) diesen String automatisch in das Datum 01.01.1970 um.
* Wenn man ein Apostroph in einem Textfeld speichert, fügt Wordpress vor das Apostroph einen Slash ein (d.h. O'Neil wird zu O/'Neil). Es scheint verschiedenen Möglichkeiten zum Korrigieren dieses Problems zu geben (siehe https://www.puravidamultimedia.com/apostrophe-and-backslash-error-in-wordpress-its-magic-quotes/ und http://thewpdojo.com/wordpress-apostrophe-backslash-problem-solved/)

Aufwand: 6 Stunden

**Comment by mathiasstocker** [comment]
- Geburtstag wird nun korrekt behandelt (bleibt leer)
- Escaping Problem gelöst
- Email-Validierung hinzugefügt
- Neuer Eintrag kann nun erstellt werden.

Aufwand: 1.25 Stunden
