### ISSUE TITLE
Tourenrückmeldung: 404

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#204]
Anwenderproblem:
Konnte die Tour erfassen
Konnte die Tour bearbeiten
Die Tourenrückmeldung konnte ich bei zwei verschiedenen Tests nicht ausführen.
Fehlermeldung: 404 Seite nicht gefunden
Konnte an Hand des Handbuches den Fehler nicht finden und korrigieren

Von #197

**Comment by ilcoron** [comment]
Hmm schwierig zu sagen was hier falsch gelaufen ist. Wenn natürlich alle Leiter versuchen Rückmeldungen zu geben, gibt es keine mehr.
Wie es zu dem 404er gekommen ist.... Keine Ahnung.

**Comment by ilcoron** [comment]
Matthias hat gefragt, wie man das reproduzieren könnte.

**Comment by mathiasstocker** [comment]
Feedback von der Testperson:

Gerne sende ich dir die Angaben betreffend der Fehlermeldung.
Es ist die Tour Oberbalm-Borisried-Vorderfultigen-Rüeggisberg: http://bergclub-test.ch/?post_type=touren&p=1966&preview_id=1966&preview_nonce=348440ea43
Und die Tour ins Fricktal: http://bergclub-test.ch/?post_type=touren&p=1888

**Comment by mathiasstocker** [comment]
Also:
Das Grundsätzliche Problem hatten wir bereits behoben (im aktuellen Master).
Wenn Ihr euch erinnert: Die Permalinks haben bei Posts mit Status "Entwurf" immer einen 404 ausgegeben.
Das war das Grundsätzliche Problem.

Nun ist es zusätzlich so, dass Leiter Posts nur ansehen können wenn Sie entweder als Leiter/Co-Leiter eingtragen sind, oder diese publiziert sind. Dies ist auf bergclub-test.ch noch nicht so (Vorschau-Link erscheint trotzdem), jedoch im aktuellen master auch bereits implementiert.

Dies ist auch SRS konform (siehe Mail unten).

Wenn der Leiter auch Entwürfe müsste in der Vorschau ansehen können, ginge das nur wenn wir ihm auch das Recht geben, fremde Posts zu editieren.

**Mail an Testperson / Pesche:**

Wir haben nun herausgefunden wo das Problem lag.
Es war nicht möglich die Vorschau von Touren zu öffnen, wenn diese noch nicht publiziert waren.
Dies ist korrigiert und wird voraussichtlich heute Abend mit dem Update auf bergclub-test.ch aktualisiert.

Grundsätzlich ist es aber so, dass die Leiter nur ihre eigenen Touren anschauen/editieren können bevor diese veröffentlicht sind.
Der Tourenchef und die Redaktion kann alle Touren anschauen und editieren.

Das heisst mit der Rolle «Leiter» sieht man nach dem Update immer noch alle Touren in der Auflistung aber der Vorschau-Link erscheint nur wenn die Tour veröffentlicht wurde oder es eine Tour ist bei welcher man als Leiter, resp. Co-Leiter eingetragen ist.

Dies ist auch Konform mit der im SRS gemachten Definition:
Leiter/in	Beiträge Kat. «Touren»		lesen**/schreiben**

** Nur zugewiesene Objekte

Grundsätzlich ist es nicht möglich, die Freigabe zum Anschauen vor der Publikation zu geben ohne auch die Rechte zum Editieren einer «fremden» Tour zu geben.
