### ISSUE TITLE
Touren: Größe der Eingabefelder

### ISSUE THREAD

**Issue by ilcoron** [PSEBergclubBern/BergclubBern#207]
Die Fenster für Info Verpflegung, Programm und Ausrüstung ist zu klein, damit man direkt beim Schreiben eine Übersicht erhält. Wohl sieht man das Geschriebene bei der Vorschau, aber es ist mühsam für Korrekturen wieder zum Bearbeiten zurück zu kehren.

Von #197

**Comment by dominikfankhauser** [comment]
Aufwand: 0.5 Stunden
