### ISSUE TITLE
Exportfunktion für Adressverwaltung

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#21]
Als Adressverantwortlicher möchte ich die Adressen der Vereinsmitglieder als Liste / Excel exportieren können.

- [ ] Exportfunktion schreiben

**Comment by Niroth** [comment]
@mathiasstocker Wurde dies bereits in #28 umgesetzt?

**Comment by mathiasstocker** [comment]
Yup
