### ISSUE TITLE
Impressum (Webdesign/Programmierung)

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#225]
Wir können da nicht "Uni Bern" schreiben aus meiner Sicht.
Entweder weglassen oder etwas im Stil von "Erstellt im Rahmen der Vorlesung "Praktikum Software Engineering" der Uni Bern.

Ich habe es in der Online-Version entfernt.

Ich habe erst jetzt gesehen, dass ein Tag verwendet wurde.
Das Problem ist, dass Sie so den Inhalt (des Tags) nicht editieren können.
Würde eher direkt in der Page-Vorlage den Inhalt einfügen (ähnlich wie jetzt online). (Plugin/ThemeAndAdminDefaults/data/pages.json) und den Tag wieder entfernen.

Die Emailadresse würde ich hier weglassen resp. die generelle Emailadresse mit dem Tag [bcb_email] einbinden - verhindert das Bots die Emailadresse lesen können, nicht im Quellcode.

**Comment by Tschav** [comment]
Impressum Content in JSON file verschoben und view blade gelöscht

Aufwand: 1.25 h
