### ISSUE TITLE
Dokumentation: Vorhandene Tags

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#226]
Mir ist (leider erst jetzt) noch etwas eingefallen:
Irgendwo sollten wir noch die Tags erklären die im WISYWIG Editor verwendet werden können:

* `[bcb_email]` => rendert einen Emaillink der nicht von Bots erkannt wird (hoffentlich) ;)
   Momentan hardcoded auf "bergclub@bergclub.ch" => Wird noch angepasst damit in WP hinterlegte Mailadresse verwendet wird (#228).
* `[bcb_calendar_link]`PDF-Kalender`[/bcb_calenderlink]` => rendert einen Link auf den PDF-Kalender des aktuellen Jahrs (z.B. für unter "Dokumente und Links") - PDF-Kalender kann durch x-beliebigen Text ersetzt werden.
* `[bcb_vorstand_table]` => rendert die Vorstands-Tabelle
* `[bcb_erweiterter_vorstand_table]` => rendert die Tabelle mit weiteren wichtigen Kontakten
* `[bcb_leiter_table]` => rendert die Tabelle mit den Tourenleitern. Je nachdem ob man sich unter "Jugend" befindet oder nicht, werden die entsprechenden Leiter angezeigt.

**Comment by Tschav** [comment]
Erste Version der Dokumentation erstellt und als input-file hinzugefügt

Aufwand: 0.5 h
