### ISSUE TITLE
Tour eingeben

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#23]
Als Mitglied des Vereins möchte ich eine Tour eingeben können im Backend

- [x] Custom Post Type
- [x] Alle Custom Fields sind vorhanden und werden validiert
- [x] Abfrage in der Eingabemaske

**Comment by ilcoron** [comment]
Ich habe den Custom Post Type mit diesm Plugin erstellt und mir dann exportieren lassen:
https://wordpress.org/plugins/custom-post-type-ui/

**Comment by ilcoron** [comment]
9.00 - 12.00 ; 12.30 - 16:30
Aufwand: 7 Stunden

**Comment by kreemer** [comment]
Architektur gemacht für OOP

Aufwand: 4 Stunden

**Comment by kreemer** [comment]
Einzelne Felder hinzugefügt. Geschaut wegen sanitize

Aufwand: 2.5 Stunden

**Comment by kreemer** [comment]
Metaboxen allgemein hinzugefügt + Gimmicks

Aufwand: 4 Stunden

**Comment by ilcoron** [comment]
Hier der relevante Auszug aus dem SRS und meine Validierung:
- Datum von (Datepicker) --- gültiges Datum
- Datum bis (Datepicker, falls leer oder identischer Wert wie "Datum von" => Eintägige Tour) --- gültiges Datum, nach oder gleich "Datum von", Eingabe übernimmt Setzen bei eintägiger Tour (!?)
- Leiter (Dropdown mit Benutzer welche Rolle "Leiter" resp. Rolle "Leiter Jugend" zugeordnet haben,
	 falls Erfasser Rolle "Leiter" resp. "Leiter Jugend" hat keine Auswahl möglich => er wird als Leiter eingetragen) --- Validierung zur Eingabe
- Co-Tourenleiter (Dropdown mit Benutzer welche eine Mitglieder-Rolle haben) --- Validierung zur Eingabe
- Art (Dropdown mit Tourenart, siehe "Stammdaten") --- Validierung zur Eingabe
- Anforderungen technisch (Dropdown mit Schwierigkeit, abhängig von Tourenart, siehe "Stammdaten", kann leer sein als "keine Angabe" angezeigt)  --- Validierung zur Eingabe
- Anforderungen konditionell (Dropdown: "Leicht", "Mittel", "Schwer")  --- Validierung zur Eingabe
- Aufstieg Höhenmeter (Textfeld, single line) --- keine Validierung (sowohl 200 als auch 200m sind gültig)
- Abstieg Höhenmeter (Textfeld, single line) --- keine Validierung (sowohl 200 als auch 200m sind gültig)
- Zeit (ohne Pause) (Textfeld, single line, Zeit ##:##) --- könnte zu Dauer umbenannt werden; Validierung ob in Format HH:MM oder H:MM mit Regex, erscheint mir sinnvoller als TimeInterval
- Besonderes (Textfeld, multi line) --- keine Validierung
- Ausbildung (Radio: Ja / Nein, Default: Nein) --- Validierung zur Eingabe
- J+S Anlass (Radio: Ja / Nein, Default: Nein)  --- Validierung zur Eingabe
- Programm (Textfeld, multi line) --- keine Validierung
- Treffpunkt (Dropdown "Bern HB, Treffpunkt", "Bern HB, auf dem Abfahrtsperron", "Bern, auf der Welle", "Anderes") --- wenn Anderes, "Anderer Treffpunkt" muss gesetzt sein
- Anderer Treffpunkt (Textfeld, single line, wird nur angezeigt wenn bei Treffpunkt "Anderes" ausgewählt) --- nur gültig wenn Treffpunkt: Anderes
- Zeit (Textfeld, single line, Zeit ##:##) --- gültige Zeit; wie Dauer
- Rückkehr: Bern an (Textfeld, single line, Zeit ##:##) --- gültige Zeit, wie Dauer
- Ausrüstung (Textfeld, multi line) --- keine Validierung
- Kartenmaterial (Textfeld, single line) --- keine Validierung
- URL Online Route (Textfeld, single line, z.B. schweizmobilplus.ch) --- muss valide URL sein , mit oder ohne www/http/https
- Verpflegung (Textfeld, multi line) --- keine Validierung
- Übernachtung (Textfeld, multi line, wird nur angezeigt wenn Datum bis definiert und nicht gleich Datum von) --- muss gesetzt sein, wenn Tour länger als ein Tag, darf nicht gesetzt sein, wenn Tour nur einen Tag lang; Ich habe mit Strings gearbeitet, ich glaube das kommt von Radiobuttons
- Kosten CHF (Textfeld, single line, Betrag #(#*).##) --- mit Regex validiert, Komma und Punkt erlaubt
- Kosten für (Textfeld, single line) --- keine Validierung
- Anmeldung bis (Datepicker) --- gültiges Datum, vor oder gleich "Datum von"
- Anmeldung an (Dropdown Leiter / Co-Leiter) --- Validierung zur Eingabe

Aufwand: 7 Stunden

**Comment by kreemer** [comment]
see #75
