### ISSUE TITLE
Handbücher Einleitung modulieren

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#231]

**Comment by Tschav** [comment]
Einleitung und Appendix in einem seperaten file und zu jedem Handbuch hinzugefügt

Aufwand: 0.5 Stunden

**Comment by Tschav** [comment]
Einleitung und Appendix sind nun in einem eigenen Ordner und nicht mehr in jedem einzelnen Handbuch ordner

Aufwand: 0.25 h
