### ISSUE TITLE
Tourbericht ergänzen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#24]
Als Tourverantwortlicher möchte ich eine vergangene Tour mit einem Bericht ergänzen.

**Comment by ilcoron** [comment]
Aufwand: 4 Stunden

**Comment by ilcoron** [comment]
Probleme: 
"Änderung gespeichert" wird doppelt angezeigt.
Die aktuell zugeordnete Tour wird nicht angezeigt, obwohl in MetaBoxTourenberichte->html() die hinzufügt, siehe TODO.

**Comment by ilcoron** [comment]
Ausserdem müssen wir noch über die Berechtigungen schaun.

**Comment by kreemer** [comment]
Aufwand: 1 Stunde
