### ISSUE TITLE
Code Review #4 Verbesserungen

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#251]
- [x] SRS fertigstellen

> Ist das SRS noch aktuell? Es enthält auf Seite 28 in roter Schrift eine Anmerkung. Diese in
schwarze Schrift ändern. Ebenfalls kleine Schreibfehler ausbessern:
• Unter Anmerkung zur Umsetzung Adress-/Benutzerverwaltung, Ausgangslage: “Das
Weitern” in “Des Weitern” ändern.
• „Zusätzliche Beispiele generierte Daten für Versandliste„ mit „Zusätzliche Beispiele
generierter Daten für Versandliste„ ersetzen.
Zu ignorieren erlaubte Neurose von mir: Ihr habt z.T. nach einem Satz einen Punkt gemacht und
zT.. nicht. Ich überlasse das euch, ob ihr es anpassen möchtet. Es beginnt in der Versionsverwaltung
und zieht sich durchs ganze SRS ;-)

- [x] Root README.md anpassen

> Unter “HowTo” “the configuration failes” mit “the configuration fails” ersetzen.

- [x] Root INSTALL.md anpassen

> Unter Plugin und Theme, zweiter Punkt “und laden den Inhalt der zwei ZIP Dateien” mit “und
laden Sie den Inhalt der zwei ZIP Dateien”. Ebenfalls unter Import der alten Daten, erster Punkt
“und installieren gemäss” mit “und installieren Sie gemäss”.

- [x] Plugin README.md  anpassen

> Unter Commands steht „@Kevin kannst du das noch ergänzen“. Entweder diesen Abschnitt löschen
oder ergänzen.

- [x] Handbücher anpassen

> Die Handbücher sind sehr gut designt. Ich fände jeweils ein Inhaltsverzeichnis mit Links zu den
Abschnitten toll, da einige ziemlich lange sind und man somit gleich zu der Probleme-bereitenden-
Stelle navigieren kann. → optional.

**Comment by Tschav** [comment]
Handbücher um Inhaltsverzeichniss erweitert

Aufwand: 0.25 Stunden

**Comment by Niroth** [comment]
Aufwand: 0.25 Stunden

**Comment by dominikfankhauser** [comment]
SRS überarbeitet und soweit sinnvoll an aktuellen Projektstand angepasst.

Aufwand: 3.5 Stunden
