### ISSUE TITLE
Exporte erstellen (FA-15 SRS)

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#28]
Als Tourenchef oder Mitglied der Redaktion will ich eine Tourenübersichtexportieren können.

**Comment by mathiasstocker** [comment]
Excel Export User/Adressen
* Mitgliederliste
* Versandliste Komplett/Programm
* Beitragsliste

Aufwand: 2.5 Stunden

**Comment by mathiasstocker** [comment]
Exporte Touren

* Jahreskalender (PDF)
* Touren (Excel)

Diverse Arbeiten

Aufwand: 12 Stunden

**Comment by mathiasstocker** [comment]
Exporte Print
* Pfarrblatt (Word)
* Quartalsprogramm (Word)

Diverse Arbeiten

Aufwand: 8.25 Stunden
