### ISSUE TITLE
Spesenverwaltung

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#29]
Als Tourenleiterwill ich die Spesen einer durchgeführten Tour abrechnen, welche vom Tourenchef genehmigt und anschliessend vom Kassier ausbezahlt werden.

**Comment by dominikfankhauser** [comment]
Workflow implementiert zum Abrechnen von Touren. 

Noch offen (Antwort von Kunde noch ausstehend):
- Validierung (inkl. Beträge in Franken)

Aufwand: 8 Stunden

**Comment by dominikfankhauser** [comment]
Validierung implementiert, Refactoring und neue Anforderungen bezüglich Auszahlung umgesetzt.

Aufwand: 3 Stunden

**Comment by mathiasstocker** [comment]
Berücksichtigung der Benutzerrechte und diverse Anpasssungen.

Aufwand: 4 Stunden
