### ISSUE TITLE
Kontaktformular

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#30]
Als Besucher möchte ich mit dem Verein per Kontaktformular in Kontakt kommen

**Comment by Niroth** [comment]
Erstes Basic-Layout des Kontaktformulars erstellt. Die Navigation wurde zudem erweitert, da noch einige Links fehlten.

Noch zu tun:
- Input-Validierung
- Versand der Daten
- Formatierung noch etwas aufbessern

Aufwand: 5 Stunden

**Comment by Niroth** [comment]
Weiter zu tun ist das Formular unter Mitgliedschaft einzubinden mit einer Abfrage, die bei Mitgliedschaftsinteresse ein entsprechendes Feld/Dropdown einblendet.

**Comment by Niroth** [comment]
Konktaktformular um required tags erweitert, Typen von
Kontaktnachrichten wie z.B. für Mitgliedschaft hinzugefügt und
Darstellung etwas angepasst.

Noch zu tun:

- Darstellung der versendeten Nachricht verbessern
- Eventuell Bootstrap Alert wenn Nachricht erfolgreich versandt?

Aufwand: 8 Stunden

**Comment by Niroth** [comment]
Kontaktformular generell überarbeitet, kann nun:

- Dynamisch erforderliche Felder anzeigen
- Nachricht ist nun HTML-formattiert
- Es erscheint ein Alert falls Nachricht versandt/nicht versandt.

Aufwand: 6 Stunden
