### ISSUE TITLE
Importfunktion

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#31]
Als Entwickler möchte ich die Daten der alten Website per Script automatisch importieren können.

**Comment by kreemer** [comment]
Aufwand: 2 Stunden

**Comment by kreemer** [comment]
Aufwand: 2 Stunden

**Comment by kreemer** [comment]
Aufwand: 3 Stunden

**Comment by kreemer** [comment]
Aufwand: 1 Stunde

**Comment by Niroth** [comment]
Aufwand: 5 Stunden

**Comment by kreemer** [comment]
User / Tour / Galerie Import angefangen

Aufwand: 4 Stunden

**Comment by kreemer** [comment]
Aufwand: 14 Stunden
