### ISSUE TITLE
Theme aufbauen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#32]
Als Besucher der Website möchte ich ein ästhetisches Theme sehen

- [ ] Theme muss mit den gewöhnlichen Browser (IE, Firefox, Chrome) angesehen werden können

Optional:
- [x] Theme sollte Responsive sein

**Comment by kellenberger** [comment]
Theme responsive gemacht mit Bootstrap. Erster Entwurf mit Platzhaltern von der Index-Page der dem Kunden gezeigt werden könnte. 

Aufwand: 3 Stunden

**Comment by mathiasstocker** [comment]
@Tschav @skell94
Schaut, dass ihr die Sache mit den Breakpoints / Grid System versteht.

Bootstrap default breakpoints:
Large (lg): >=1200px
Medium (md): >=992px <1200px
Small (sm): >=768px <992px
Extra Small (xs): <768px

Beim Gridsystem wird die aktuelle Breite des übergeordneten Containers in 12 Einheiten unterteilt.
```
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6">
       Inhalt
    </div>
  </div>
</div>
```
=> Dies bedeutet solange der Breakpoint Medium (md) oder grösser ist (lg) wird, hat der Inhalt die Hälfte der Breite des übergeordneten Containers zur Verfügung, wenn der Breakpoint kleiner ist (s, xs) erscheint er in voller Breite.

```
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-8 col-sm-6 col-lg-4">
       Erste Zelle
    </div>
    <div class="col-xs-10 col-sm-6 col-lg-8">
       Zweite Zelle
    </div>
  </div>
</div>
```
Hier wird die erste Zelle bei Large mit 1/3 Breite festgelegt, die zweite mit 2/3 Breite.
Für Medium und Small werden beide Zellen mit 1/2 Breite festgelegt.
Für Extra Small ist die erste Zelle mit 8/12 Breite festgelegt, die zweite mit 10/12 => Da zusammen mehr als 12/12 erscheinen diese untereinander.

Ihr könnt auch mit hidden-[size] und visible-[size] gewisse Element für bestimmte Breakpoints aus- resp. einblenden.

https://www.w3schools.com/bootstrap/bootstrap_grid_system.asp
http://getbootstrap.com/css/#grid
http://www.ryanwright.me/cookbook/bootstrap/container-vs-container-fluid

**Comment by mathiasstocker** [comment]
@Tschav @skell94 
Mit Kunde abgeklärt:
Login wird **nicht** verlinkt im Frontend.

**Comment by mathiasstocker** [comment]
@skell94
Kunde hat eine Bilderauswahl für Startseite gesendet.
Dropbox: "PSE 2017/Unterlagen Kunde/Bilder Startseite"
Order mit Originalbildern und Ordner mit optimierten (so gut es ging) Bildern mit geeignetem Ausschnitt (1920 x 1080 @ 72dpi, JPEG 60%)

**Comment by Tschav** [comment]
Vorstand Beispiel-Seite erstellt mit Dummy-Inhalten (statisch im Code abgelegt); CSS Anpassungen (responsive Tabelle, Bootstrap grid layout)

Aufwand: 4 Stunden

**Comment by Tschav** [comment]
Login Page aus Menu entfernt; Bergclub Bern Titel (Header) zu Homepage verlinkt; Mitteilungen Loop zu Startbildschirm hinzugefügt

Aufwand: 0.5 Stunden

**Comment by kellenberger** [comment]
Bilder für Index geändert, Caroussel korrigiert, mobile Ansicht verbessert.

Aufwand: 3 Stunden

**Comment by kellenberger** [comment]
Funktionalität für Jugend Seite implementiert

Aufwand: 2 Stunden

**Comment by mathiasstocker** [comment]
@skell94 @Tschav 

Verwendet im Loop folgendes um den Permalink zu verwenden:
`<a href="<?php the_permalink(); ?>"><?php the_title() ?></a>`


Dann wird der richtige Link ohne Parameter verwendet.

Gruss Mäthu

**Comment by kellenberger** [comment]
Jugend ausgebaut, funktioniert nun auf allen Seiten

Aufwand: 3 Stunden

**Comment by mathiasstocker** [comment]
* Unnötige Funktionalitäten aus theme template entfernt
* Theme generell aufgeräumt, unnötiges entfernt und optimiert
* Sass hinzugefügt
* Adminmenü "Bericht" wird in "Mitteilungen" umgeschrieben
* "Mitteilungen" als Standardkategorie unter "Mitteilungen", Kategorieauswahl wird ausgeblendet
* Kategorien, Menu und Page Generierung neu im Plugin, Submodul " (ThemeAndAdminDefaults) sollte zuständig sein für Positionierung, nicht erstellung)
* Frontend Menü "Mitteilungen" ist jetzt Kategorienarchiv (archive.php zuständig)
* Frontend Menü "Tourenprogramm" ist jetzt Post-Type-Archiv (archive-touren.php)
* Frontend Menü "Tourenberichte" ist jetzt Post-Type-Archiv (archive.php)
* Support für subdomain jugend.* hinzugefügt, urls werden entsprechenden umgeschrieben
* Im Theme werden sämtliche styles und scripts nun über wp_enqueue bei Bedarf hinzugefügt
* Hintergrundbilder werden als inline style (<style></style> im head) mit wp_add_inline_style hinzugefügt
* Alle Hintergrundbilder aus Ordner img/carousel werden automatisch und in zufälliger Reihenfolge hinzugefügt
* Simples Math Captcha hinzugefügt
* Notice (Alert) Funktionalität für Bootstrap, analog FlashMessage im Plugin hinzugefügt
* Funktion bcb_email($email) im Plugin hinzugefügt, liefert "leeren" Link mit encodierter Emailadresse welche im Frontend mit jQuery zu Emailadresse umgewandelt wird (anti-spam)
* TagHelper im Plugin hinzugefügt (Ermöglicht Registrierung von Tags und Zuordnung von Funktionen/Methoden durch welche der Tag im content ersetzt wird. z.B. kann mit [bcb_email] die Emailadresse des Bergclubs an beliebiger Stelle eingefügt werden.
* Änderungen von Marcel (Darstellung Vorstand) integriert
* Spezifische icon font für touren attribute erstellt (fontastic.me)
* Vorschlag für tourenauflistung homepage erstellt
* Und noch einige kleine Dinge mehr was ich nicht notiert habe ;)

Aufwand: 12 Stunden

**Comment by mathiasstocker** [comment]
Diverse Anpassungen Tourenprogramm/Tourenberichte

Aufwand: 3.5 Stunden
