### ISSUE TITLE
Globale Einstellungen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#33]
Als Administrator der Website möchte ich Grundeinstellungen für Touren vorgeben können.

- [x] WP-Admin Menüpunkt erstellen
- [x] Schwierigkeitsgrad, Mitgliederbeiträge, etc. einstellbar

**Comment by ilcoron** [comment]
Hallo Dominik,

Ich habe mich kurz mit der Materie wegen der Touren beschäftigt. Vielleicht hilft dir der Code aus diesem Plugin: https://wordpress.org/plugins/advanced-custom-fields/ -> das Plugin selbst können wir wohl nicht benutzen aber vielleicht hilft ja der Source Code...

Gruss
Timm

**Comment by dominikfankhauser** [comment]
WP-Admin Menüpunkt heisst "Stammdaten".

Aufwand: 6.5 Stunden
