### ISSUE TITLE
Mitteilungen als Kategorie erfassen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#35]
- [ ] Kategorie per Theme erstellen
- [ ] Loop erstellen um die Mitteilungen als Liste zu rendern
- [ ] Beispieltext erstellen

**Comment by Tschav** [comment]
Kategorie Mitteilungen erstellt und Dummy Mitteilungen hinzugefügt, die in einer Tabelle aufgeführt werden.

Aufwand: 5 Stunden

**Comment by Tschav** [comment]
Test import von Mitteilungen; CSS Anpassungen; Post-Navigation hinzugefügt

Aufwand: 4 Stunden
