### ISSUE TITLE
Präsentation Testkonzept

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#4]

**Comment by ilcoron** [comment]
Ersten Entwurf zum Testkonzept aufgesetzt.

Aufwand: 1 Stunden

**Comment by ilcoron** [comment]
Präsentation

Aufwand: 5 Stunden

**Comment by ilcoron** [comment]
Testkonzept ausarbeiten

Aufwand: 1 Stunde
