### ISSUE TITLE
FlashMessage gibt zwei mal die Meldung zurück

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#52]
Nachdem man eine Nachricht in die FlashMessage geschickt hat, wird diese bei show zweimal ausgegeben.
Vorgehen zum reproduzieren:
1. Branch TourMetaBoxes auschecken
2. Neue Tour erfassen mit ungültigem Datum (vlt. javascript abschalten, um den Datepicker zu entfernen)

**Comment by mathiasstocker** [comment]
FlashMessage::add wird zweimal aufgerufen. Fehler nicht im FlashMessage.
Habe FlashMessage:add aber so angepasst, dass die exakte selbe Nachricht nicht mehr als einmal geadded wird.

**Comment by mathiasstocker** [comment]
@kreemer Können wir das schliessen? War ja nicht Problem von FlashMessage...
