### ISSUE TITLE
TASK [Run `wp options update`] vor TASK [Run `wp theme install`]

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#53]
@kreemer kannst du den Task welcher die permalink structure setzt vor der installation des themes ausführen lassen? Bei der Aktivierung des themes werden posts erstellt und diese erhalten so einen "falschen" permalink (/archives/id), da der Generator die neuen options noch nicht hat.

**Comment by kreemer** [comment]
Ansible konfiguriert:

Aufwand: 2 Stunden
