### ISSUE TITLE
Software Requirements Specification Version 1

### ISSUE THREAD

**Issue by Niroth** [PSEBergclubBern/BergclubBern#7]

**Comment by mathiasstocker** [comment]
Lastenheft und weitere Unterlagen Kunden durchforstet und Übersicht "Muss" erstellt, sowie Unklarheiten und Lösungsansätze ausgearbeitet

Danach Mail an Kunde, da telefonisch nicht erreicht.

Aufwand: 3.5 Stunden

**Comment by mathiasstocker** [comment]
Telefon mit Kunde, besprechen Mail vom Vortag (Unklarheiten / Lösungsansätze).
Zusammenfassung Telefonat unter "Kundenkontakt".

Aufwand: 0.75 Stunden

**Comment by mathiasstocker** [comment]
Treffen mit @dominikfankhauser um Detailfragen SRS zu besprechen

Aufwand: 2.5 Stunden

**Comment by dominikfankhauser** [comment]
Durchschauen der Unterlagen des Kunden; Teil Tourenverwaltung in SRS geschrieben.

Aufwand: 5 Stunden

**Comment by Tschav** [comment]
Unterlagen des Kunden durchsehen und Teil Adressverwaltung / Benutzerverwaltung im SRS geschrieben.

Aufwand: 3.5 Stunden

**Comment by Niroth** [comment]
Requirements Öffentlicher Bereich inkl. Use Cases

Aufwand: 2.5 Stunden

**Comment by mathiasstocker** [comment]
Überprüfen SRS hinsichtlich WordPress-Workflow. Überarbeitung Benutzerrollen. Überprüfen, Überarbeiten und Abgleich Use Cases und Requirements. Einfügen und Formatieren Benutzerrollen und Requirements.

Aufwand: 6 Stunden

**Comment by dominikfankhauser** [comment]
Zusammenfügen der einzelnen Teildokumente, UML-Diagramme ergänzt und Dokument überprüft.

Aufwand: 2.5 Stunden
