### ISSUE TITLE
Touren: Custom Fields

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#75]
- "Rückkehr" soll kein Zeitfeld mehr, sondern freies Feld sein (so dass z.B. auch "abends") erfasst werden kann, falls Zeitpunkt nicht genauer definiert werden kann. --- done

- "Kosten" & "Anmeldung an" => Pflichtfelder. ---done

**Comment by ilcoron** [comment]
Ausserdem muss noch der Eingabetyp der Radiobuttons überprüft werden.

**Comment by mathiasstocker** [comment]
@kreemer @ilcoron 

Wägem toure speichere, dass isch würklech no chli verflixt.
Ha unger touren_save_correct e Vorschlag gmacht wo funktioniert.
Isch ned wunderschön, vellech findet dir no e besseri lösig...

1. Luegt dass der hook für save_post nur einisch ufgruefe werd
2. Setzt der post status uf e letscht status wo der post vorem spichere gha hett zrügg faus dValidierig ned i.O. (resp. nimmts as letscht status draft we dä auto-draft isch (vo post-new.php)).
3. Füre Entwurf ischs tatsächlech ned möglech ne ned zspichere, we fäuder fähle - e luege das mit em chund a. Aso es gieng we me der Status uf 'auto-draft' zrüggsetzt aber de setzts ou immer der titel uf läär, resp. luegt ned obs e titel hett.
4. Damits für "Review" (pending) und "Published" (publish) die zuesätzleche Fäuder validiert, resp. für "Draft" (draft) ned, müest der ir MetaBox bir Zile 128 e lösig finge (z.B. dass der am isValid der aktuelle post status chöit mitgäh zum entscheide)

Luegets bitte mitenand a.

Betreffend wär darf editiere, veröffentlichung beaträge und publiziere funktioniert dass scho mit de Roue:
users (pw = login):
- leiter
- tourenchef
- redaktion

**Comment by ilcoron** [comment]
Momentan kann der Tourenchef Touren nicht bearbeiten

**Comment by ilcoron** [comment]
Aufwand: 7 Stunden
