### ISSUE TITLE
Enwicklungsumgebung aufbauen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#8]
Entwicklungsumgebung aufbauen in allen Modulen und Dokumentation dazu erstellen

**Comment by kreemer** [comment]
Konfiguration erstellt / vccw vs. Scotchbox abgeklärt / scratch theme und plugin

Aufwand: 3.5 Stunden

**Comment by kreemer** [comment]
Ansible script angepasst

Aufwand: 2 Stunden

**Comment by kellenberger** [comment]
Konfiguration Vagrant/VCCM in BergClubPlugin
Aufwand: 3 Stunden

**Comment by kreemer** [comment]
Windows konfiguration angepasst

Aufwand: 0.5 Stunde

**Comment by ilcoron** [comment]
Umgebung auf Windows zum Laufen gebracht; PHPUnit installiert; Travis Integration

Aufwand: 7 Stunden
