### ISSUE TITLE
Ansicht Tour/Touren Front-End erstellen

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#82]

**Comment by kellenberger** [comment]
Single Touren und Übersichtsseite erstellt, gestylt und mit custom_attributes versehen. Noch nicht fertig. Müssen teilweise noch mit Mitgliedern verknüpft werden etc.

Aufwand: 7 Stunden

**Comment by kellenberger** [comment]
Refactoring, neue Felder hinzugefügt, Userabfragen etc.

Aufwand: 6 Stunden
