### ISSUE TITLE
Abklären mit Kunde wegen aktuellen Benutzer / Rolle

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#91]
Welche Benutzer (inkl. Adressen) haben welche Rolle?
Liste erstellen

**Comment by mathiasstocker** [comment]
Hier ersichtlich:
http://bergclub.ch/kontakt/kontakt.php

Leiter hier:
http://bergclub.ch/leiter/leiter_bcb.php

Leiter Jugend hier:
http://bergclub.ch/leiter/leiter_bcbj.php
