### ISSUE TITLE
Abklären wegen Tabellenplugin

### ISSUE THREAD

**Issue by kreemer** [PSEBergclubBern/BergclubBern#92]
MIt Kunde abklären, ob visualcomposer oder einfaches tabellenplugin

**Comment by Niroth** [comment]
Aufwand: 3 Stunden

**Comment by Niroth** [comment]
Plugin TinyMCE Advanced muss noch in Vagrant-Installation integriert werden.

**Comment by mathiasstocker** [comment]
@kreemer 
Kannst du das im provision file integrieren?
