### ISSUE TITLE
Tourenvalidierung mit SRS abgleichen

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#97]
Kevin hat Validierung korrigiert, ist gemerget.

Folgende Punkte sind noch nicht SRS konform oder sonst nicht ideal:

* Validierungsmeldung "Mehrtägige Touren müssen eine Übernachtung beinhalten"
  Aus meiner Sicht unverständlich. Besser
  "Bei mehrtägigen Touren muss das Feld "Übernachtung" ausgefüllt werden."
  
* Validierungsmeldung "Kosten (CHF)" muss das Format #(#*).## oder #(#*),## haben"
  Diese Formatdefinitionen verstehen wir, aber nicht der gewöhnliche Leiter.
  Formatprüfung auf #(#*).## würde gemäss SRS genügen.
  Ich würde hier die Formatsprüfung nicht so streng sehen, also Werte wie 30, 30.5 u.s.w. auch zulassen.
  Eventuell einfach auf `isnumeric` Prüfen, falls ja den Wert mit `number_format($var, 2, '.', '')` formatieren.
  Und dann als Fehlermeldung (falls `!isnumeric`) "Kosten CHF muss im Format 0.00 angegeben werden."

* Feld "Anmeldung an": Sollte nur Leiter oder Co-Leiter auswählbar sein 

* Feld "Dauer": Sollte "Dauer (ohne Pause)" heissen

* Feld "Verpflegung" ist Pflichtfeld (ausser für Entwurf)

**Comment by kreemer** [comment]
Aufwand: 2 Stunden
