### ISSUE TITLE
Datumsfelder Touren

### ISSUE THREAD

**Issue by mathiasstocker** [PSEBergclubBern/BergclubBern#99]
Diese sollten im Format Y-m-d abgelegt werden und d.m.Y angezeigt werden.

Grund: Abfrage von Posts die in der Vergangenheit/Zukunft liegen.

Bitte nach Erledigung geöffnet lassen und neu zuweisen, wird an folgenden Orten benötigt und muss dort angepasst werden:
* Startseite
* Tourenprogramm
* Export
* Auswahl für Zuordnung Tourenbericht

**Comment by kreemer** [comment]
Aufwand: 1 Stunde
